In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from PIL import Image

In [2]:
train = pd.read_csv('mnist_train.csv')

In [3]:
_1st_weights = pd.read_csv('1st_weights')
_1st_weights = _1st_weights.ix[:,'0':]
_1st_weights = _1st_weights.as_matrix()

_1st_biases = pd.read_csv('1st_biases')
_1st_biases = _1st_biases.ix[:,'0':]
_1st_biases = _1st_biases.as_matrix()
_1st_biases = np.reshape(_1st_biases, (1000,))
np.shape(_1st_biases)

(1000,)

In [4]:
_2nd_weights = pd.read_csv('2nd_weights')
_2nd_weights = _2nd_weights.ix[:,'0':]
_2nd_weights = _2nd_weights.as_matrix()

_2nd_biases = pd.read_csv('2nd_biases')
_2nd_biases = _2nd_biases.ix[:,'0':]
_2nd_biases = _2nd_biases.as_matrix()
_2nd_biases = np.reshape(_2nd_biases, (1300,))

In [5]:
_3rd_weights = pd.read_csv('3rd_weights')
_3rd_weights = _3rd_weights.ix[:,'0':]
_3rd_weights = _3rd_weights.as_matrix()

_3rd_biases = pd.read_csv('3rd_biases')
_3rd_biases = _3rd_biases.ix[:,'0':]
_3rd_biases = _3rd_biases.as_matrix()
_3rd_biases = np.reshape(_3rd_biases, (1500,))

In [6]:
_lst_weights = pd.read_csv('lst_weights')
_lst_weights = _lst_weights.ix[:,'0':]
_lst_weights = _lst_weights.as_matrix()

_lst_biases = pd.read_csv('lst_biases')
_lst_biases = _lst_biases.ix[:,'0':]
_lst_biases = _lst_biases.as_matrix()
_lst_biases = np.reshape(_lst_biases, (10,))

In [7]:
img = Image.open('image.bmp')
arr = np.array(img)

In [8]:
mean = np.mean(arr)
std = np.std(arr)
zero_mean = arr - mean
image = zero_mean/std
np.shape(image)

(28, 28)

In [9]:
dict_x_train = train.ix[:,'0':]
pixel_train = dict_x_train.as_matrix()
dict_y_train = train.ix[:,'5']
label = dict_y_train.as_matrix()

###############################################
mean_train = np.mean(pixel_train,axis = 1)
std_train = np.std(pixel_train,axis = 1)
#############################################

###############################################
mean_temp_train = np.tile(mean_train,[784,1])
mean_temp_train = mean_temp_train.transpose()

std_temp_train = np.tile(std_train,[784,1])
std_temp_train = std_temp_train.transpose()
############################################

###########################################
zero_mean_train = pixel_train - mean_temp_train
data = zero_mean_train/std_temp_train
##############################################


#############################################
train_data = data
###########################################


###########################################
data = train_data[0:42000,:]
validate = train_data[42001:54000,:]
testdata = train_data[54001:59998,:]

label_data = label[0:42000]
label_validate = label[42001:54000]
label_test = label[54001:59998]
##############################################

In [10]:
def one_hot_encoding(x):
    temp = np.zeros((len(x), 10))             #10 classes
    temp[np.arange(len(x)), x] = 1
    return temp

In [11]:
img_size = 28

img_size_flat = img_size * img_size

img_shape = (img_size, img_size)

first_layer = 1000

second_layer = 1300

third_layer = 1500

num_classes = 10

In [12]:
x = tf.placeholder(tf.float32, [None, img_size_flat])
y_true = tf.placeholder(tf.float32, [None, num_classes])
y_true_cls = tf.placeholder(tf.int64, [None])

In [13]:
first_weights = tf.Variable(tf.random_normal([img_size_flat, first_layer]))
first_biases = tf.Variable(tf.zeros([first_layer]))

second_weights = tf.Variable(tf.random_normal([first_layer, second_layer]))
second_biases = tf.Variable(tf.zeros([second_layer]))

third_weights = tf.Variable(tf.random_normal([second_layer, third_layer]))
third_biases = tf.Variable(tf.zeros([third_layer]))

last_weights = tf.Variable(tf.random_normal([third_layer,num_classes]))
last_biases = tf.Variable(tf.zeros([num_classes]))

In [14]:
z1 = tf.matmul(x,first_weights) + first_biases
a1 = tf.nn.relu(z1)

z2 = tf.matmul(a1, second_weights) + second_biases
a2 = tf.nn.relu(z2)

z3 = tf.matmul(a2, third_weights) + third_biases
a3 = tf.nn.relu(z3)

logits = tf.matmul(a3, last_weights) + last_biases

In [15]:
y_pred = tf.nn.softmax(logits)
y_pred_cls = tf.argmax(y_pred, dimension=1)
y_pred

<tf.Tensor 'Softmax:0' shape=(?, 10) dtype=float32>

In [16]:
testing = train.ix['43000':'43150',:]
dict_x_testing = train.ix['43000':'43150','0':]
pixel_testing = dict_x_testing.as_matrix()


dict_y_testing = train.ix['43000':'43150','5']
dict_y_testing
label_testing = dict_y_testing.as_matrix()
label_testing

array([9, 2, 1, 8, 7, 1, 1, 8, 4, 4, 0, 3, 0, 3, 4, 1, 1, 8, 7, 0, 5, 4, 7,
       7, 1, 4, 3, 9, 3, 1, 3, 2, 1, 9, 6, 7, 9, 4, 7, 2, 4, 8, 3, 1, 0, 7,
       2, 5, 6, 0, 8, 7, 1, 6, 5, 5, 9, 9, 0, 8, 6, 8, 6, 3, 3, 5, 3, 4, 8,
       3, 1, 8, 4, 0, 7, 3, 2, 4, 2, 3, 0, 7, 0, 5, 1, 9, 7, 0, 7, 3, 8, 0,
       9, 9, 6, 8, 8, 5, 8, 3, 2, 0, 3, 7, 2, 4, 9, 7, 8, 8, 5, 4, 2, 9, 6,
       2, 2, 1, 4, 9, 8, 2, 4, 2, 6, 3, 5, 1, 0, 4, 1, 3, 2, 0, 3, 5, 4, 9,
       5, 3, 6, 1, 7, 5, 8, 9, 9, 5, 0, 4, 1], dtype=int64)

In [17]:
image = np.reshape(image,(1,28*28))
image=np.float32(image)
type(image[0,0])

numpy.float32

In [20]:
#feed_label_testing = one_hot_encoding(label_testing)
#testing_class = np.array([label.argmax() for label in feed_label_testing])
feed_dict_testing = {x: pixel_testing ,
                     
                      first_weights: _1st_weights,
                      first_biases: _1st_biases,
                      
                      second_weights: _2nd_weights,
                      second_biases: _2nd_biases,
                      
                      third_weights: _3rd_weights,
                      third_biases: _3rd_biases,
                      
                      last_weights: _lst_weights,
                      last_biases: _lst_biases}

In [21]:
session = tf.Session()
session.run(tf.global_variables_initializer())
session.run(y_pred_cls, feed_dict = feed_dict_testing)

array([4, 2, 1, 8, 7, 1, 1, 8, 9, 4, 0, 1, 0, 3, 4, 1, 1, 8, 7, 0, 5, 4, 7,
       7, 1, 4, 3, 9, 3, 1, 3, 2, 1, 5, 6, 7, 8, 4, 7, 2, 4, 8, 8, 1, 0, 7,
       2, 5, 6, 0, 8, 7, 1, 6, 5, 5, 9, 9, 8, 8, 6, 8, 6, 3, 3, 5, 3, 4, 8,
       3, 1, 8, 4, 0, 7, 3, 2, 4, 8, 3, 0, 7, 0, 5, 1, 9, 7, 0, 1, 3, 8, 0,
       9, 9, 8, 8, 8, 5, 8, 3, 2, 0, 3, 7, 2, 4, 9, 7, 8, 8, 8, 4, 2, 9, 6,
       2, 2, 1, 4, 9, 8, 2, 4, 2, 6, 6, 5, 1, 0, 4, 1, 3, 2, 0, 3, 5, 4, 9,
       5, 3, 6, 1, 7, 5, 8, 9, 9, 5, 0, 4, 1], dtype=int64)

In [20]:
label_testing

array([9, 2, 1, 8, 7, 1, 1, 8, 4, 4, 0, 3, 0, 3, 4, 1, 1, 8, 7, 0, 5, 4, 7,
       7, 1, 4, 3, 9, 3, 1, 3, 2, 1, 9, 6, 7, 9, 4, 7, 2, 4, 8, 3, 1, 0, 7,
       2, 5, 6, 0, 8, 7, 1, 6, 5, 5, 9, 9, 0, 8, 6, 8, 6, 3, 3, 5, 3, 4, 8,
       3, 1, 8, 4, 0, 7, 3, 2, 4, 2, 3, 0, 7, 0, 5, 1, 9, 7, 0, 7, 3, 8, 0,
       9, 9, 6, 8, 8, 5, 8, 3, 2, 0, 3, 7, 2, 4, 9, 7, 8, 8, 5, 4, 2, 9, 6,
       2, 2, 1, 4, 9, 8, 2, 4, 2, 6, 3, 5, 1, 0, 4, 1, 3, 2, 0, 3, 5, 4, 9,
       5, 3, 6, 1, 7, 5, 8, 9, 9, 5, 0, 4, 1], dtype=int64)